# Generated by Django 3.2 on 2021-04-21 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('is_correct', models.BooleanField(null=True, verbose_name='Is correct?')),
                ('likesAmount', models.IntegerField(default=0, null=True, verbose_name='Amount of likes')),
                ('dislikesAmount', models.IntegerField(default=0, null=True, verbose_name='Amount of dislikes')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(max_length=1024, null=True, upload_to='', verbose_name='Avatar')),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=258, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('answersAmount', models.IntegerField(default=0, verbose_name='answersAmount')),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='Author ID')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='app.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='LikeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.BooleanField(default=True, null=True, verbose_name='Like/Dislike')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question', verbose_name='Question ID')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Лайк на вопрос',
                'verbose_name_plural': 'Лайки на вопросы',
            },
        ),
        migrations.CreateModel(
            name='LikeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.BooleanField(default=True, null=True, verbose_name='Like/Dislike')),
                ('answerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.answer', verbose_name='Ответ')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Answer feedback',
                'verbose_name_plural': 'Answers feedback',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='authorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='Author ID'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question', verbose_name='Question ID'),
        ),
    ]
