# Generated by Django 3.2 on 2021-04-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210421_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
        migrations.AddField(
            model_name='question',
            name='dislikesAmount',
            field=models.IntegerField(default=0, null=True, verbose_name='Amount of dislikes'),
        ),
        migrations.AddField(
            model_name='question',
            name='likesAmount',
            field=models.IntegerField(default=0, null=True, verbose_name='Amount of likes'),
        ),
    ]
