# Generated by Django 3.2 on 2021-04-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210421_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='Popularity'),
        ),
    ]
