# Generated by Django 3.2 on 2021-04-26 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_likequestion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.answer', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='likeanswer',
            name='opinion',
            field=models.BooleanField(default=True, verbose_name='Like/Dislike'),
        ),
    ]
